pub mod approvals;
pub mod assignments;
pub mod backlog;
pub mod bootstrap;
pub mod bundle;
pub mod cli;
pub mod compat;
pub mod config;
pub mod dispatch;
pub mod events;
pub mod evidence;
pub mod execution_mode;
pub mod execution_policy;
pub mod findings;
pub mod git_readiness;
pub mod guidance;
pub mod host_guidance;
pub mod host_lifecycle;
pub mod integrations;
pub mod leases;
pub mod models;
pub mod process;
pub mod project;
pub mod reconcile;
pub mod server;
pub mod state;
pub mod storage;
pub mod tasks;
pub mod workspace;

mod git_trailers;

pub use server::{serve_stdio, PlatypusMcp};
